[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 200

remappings = []

[rpc_endpoints]
mantle-sepolia = "${MANTLE_RPC_URL}"
base-sepolia = "${BASE_RPC_URL}"

[etherscan]
mantle-sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=84532" }
base-sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=5003" }

