[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = []

[rpc_endpoints]
mantle-sepolia = "${MANTLE_RPC_URL}"

[etherscan]
mantle-sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=84532" }
